# Generated by Django 2.2.6 on 2019-12-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20191214_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='time_reported',
            new_name='created_date',
        ),
    ]
