# Generated by Django 2.2.6 on 2019-12-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='nickname',
            new_name='name',
        ),
    ]
