# Generated by Django 2.2.6 on 2020-01-09 02:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200109_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='department',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Database', 'Database'), ('User Auth', 'User Auth'), ('Styling', 'Styling'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], default='Back-end', max_length=100),
        ),
    ]
