# Generated by Django 2.2.6 on 2019-11-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=600)),
                ('time_reported', models.DateTimeField()),
                ('reporter', models.CharField(max_length=80)),
                ('report_type', models.CharField(choices=[('bug', 'Bug'), ('vulnerability', 'Vulnerability'), ('feature request', 'Feature Request')], default='bug', max_length=6)),
                ('department', models.CharField(choices=[('db', 'Database'), ('auth', 'User Auth'), ('styling', 'Styling'), ('front', 'Front-end App'), ('back', 'Back-end App')], default='back', max_length=6)),
            ],
        ),
    ]
