# Generated by Django 2.2.6 on 2019-11-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_report_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(choices=[('Database', 'Database'), ('User Auth', 'User Auth'), ('Styling', 'Styling'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], default='back', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('vulnerability', 'Vulnerability'), ('feature request', 'Feature Request')], default='bug', max_length=16),
        ),
    ]
