# Generated by Django 2.2.6 on 2019-11-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20191108_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Vulnerability', 'Vulnerability'), ('Feature request', 'Feature Request')], default='bug', max_length=16),
        ),
    ]
