# Generated by Django 2.2.6 on 2019-11-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20191108_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='log',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(default='', max_length=600),
        ),
    ]
