# Generated by Django 2.2.6 on 2019-11-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20191113_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='log',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(max_length=600),
        ),
    ]
