# Generated by Django 2.2.6 on 2019-11-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20191113_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='log',
        ),
        migrations.RemoveField(
            model_name='report',
            name='note',
        ),
    ]
