# Generated by Django 2.2.6 on 2019-11-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20191113_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='error_log',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(default='', max_length=600),
        ),
    ]
