# Generated by Django 2.2.6 on 2019-12-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20191113_0541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
